name: Argus
channels: 
  - conda-forge
  - defaults 
dependencies:
  - python = 3.12
  - scikit-sparse == 0.4.14
  - libstempo >= 2.5.0
  - enterprise-pulsar >= 3.4
  - jax >= 0.5.2 
  - jaxlib >= 0.5.2 
  - flax >=0.10.2
