#!/usr/bin/env python
"""White-noise diagnostics behind the OU-adequacy step-3 data-treatment findings.

For every pulsar staged for step 3 (``data/ng15_single_binned/<PSR>/<PSR>.feather``, from
``slurm_scripts/ng15_single_prep.sh``) this compares two white-noise levels for the 30-day
inverse-variance-binned data:

* **Argus**: what the filter uses, EFAC on the binned error and the per-TOA EQUAD added
  AFTER binning, ``efac^2 sigma_bin^2 + equad^2``.
* **binned**: the white noise of the binned data when EFAC/EQUAD are applied per TOA
  BEFORE inverse-variance binning, ``1 / sum_i 1/(efac^2 sigma_i^2 + equad^2)``.

It reports:

* ``chi2/N`` of the binned residuals against each level. A value well below 1 means the
  residuals scatter less than their own white noise, i.e. degrees of freedom were removed
  upstream (the DMX-subtraction hypothesis in ``notes/RESULTS_ou_adequacy_ng15.md``).
* ``EQUAD inflation`` = 0.5 log10 of the ratio of the two white levels, each summarised as
  ``1/mean(1/var)`` over epochs: the same white-floor summary ``ng15_red_noise_budget.py``
  uses, expressed in dex of rms.

CPU only, seconds:

    JAX_PLATFORMS=cpu python workflows/ng15_sgwb_demo/scripts/ng15_white_noise_diagnostics.py
"""

import argparse
import json
import os

import numpy as np
import pyarrow.feather as pf

_WF = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(_WF, "data")
DEFAULT_NOTES = os.path.join(_WF, "notes", "ng15_white_noise_diagnostics.md")
SEC_PER_DAY = 86400.0
CADENCE_DAYS = 30.0


def diagnose(psr, noise):
    """Per-pulsar white levels and chi2/N; raw and binned feathers must share epochs."""
    raw = pf.read_table(
        os.path.join(DATA, "ng15_single_raw", f"{psr}.feather")
    ).to_pandas()
    binned = pf.read_table(
        os.path.join(DATA, "ng15_single_binned", psr, f"{psr}.feather")
    ).to_pandas()
    efac, equad2 = noise["efac"], 10.0 ** (2.0 * noise["equad"])

    mjd = np.asarray(raw["toas"]) / SEC_PER_DAY
    err = np.asarray(raw["toaerrs"])
    idx = np.floor((mjd - mjd.min()) / CADENCE_DAYS).astype(int)
    occupied = np.unique(idx)
    var_binned = (
        1.0 / np.bincount(idx, weights=1.0 / (efac**2 * err**2 + equad2))[occupied]
    )
    var_argus = efac**2 * np.asarray(binned["toaerrs"]) ** 2 + equad2
    res = np.asarray(binned["residuals"])
    if res.size != occupied.size:
        raise ValueError(
            f"{psr}: {res.size} binned rows vs {occupied.size} occupied bins"
        )

    def floor(v):
        return 1.0 / np.mean(1.0 / v)

    return {
        "psr": psr,
        "toa_per_bin": err.size / occupied.size,
        "log10_equad": noise["equad"],
        "chi2N_argus": float(np.mean(res**2 / var_argus)),
        "chi2N_binned": float(np.mean(res**2 / var_binned)),
        "equad_inflation_dex": float(
            0.5 * np.log10(floor(var_argus) / floor(var_binned))
        ),
    }


def main():
    """Diagnose every staged pulsar and write the markdown table."""
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--noise-json", default=os.path.join(DATA, "ng15_psr_noise_full.json")
    )
    ap.add_argument("--notes", default=DEFAULT_NOTES)
    args = ap.parse_args()

    noise = json.load(open(args.noise_json))
    psrs = sorted(os.listdir(os.path.join(DATA, "ng15_single_binned")))
    rows = [diagnose(p, noise[p]) for p in psrs]

    lines = [
        "# NG15 single-pulsar white-noise diagnostics (OU-adequacy step 3)",
        "",
        "Generated by `scripts/ng15_white_noise_diagnostics.py`. chi2/N of the 30-day binned "
        "residuals against the white level Argus uses (EQUAD added after binning) and against "
        "the correctly binned white level (EFAC/EQUAD per TOA, then binned). EQUAD inflation "
        "= 0.5 log10 of the ratio of the two levels, each summarised as 1/mean(1/var).",
        "",
        "| pulsar | TOA/bin | log10 EQUAD | chi2/N (Argus) | chi2/N (binned) "
        "| EQUAD inflation [dex rms] |",
        "|---|---|---|---|---|---|",
    ]
    for r in sorted(rows, key=lambda r: r["chi2N_binned"]):
        lines.append(
            f"| {r['psr']} | {r['toa_per_bin']:.1f} | {r['log10_equad']:.2f} | "
            f"{r['chi2N_argus']:.2f} | {r['chi2N_binned']:.2f} | "
            f"{r['equad_inflation_dex']:+.2f} |"
        )
    with open(args.notes, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    for r in rows:
        print(
            f"{r['psr']:<12} chi2/N argus {r['chi2N_argus']:8.2f} binned "
            f"{r['chi2N_binned']:8.2f}  inflation {r['equad_inflation_dex']:+.2f} dex"
        )


if __name__ == "__main__":
    main()
