on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 'latest'

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Build draft PDF
        run: |
          pandoc docs/joss/paper.md \
            --from markdown \
            --to pdf \
            --output docs/joss/paper.pdf \
            --pdf-engine=pdflatex \
            --template=https://raw.githubusercontent.com/openjournals/joss-papers/master/joss-template.latex \
            --citeproc

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: docs/joss/paper.pdf
