

name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

# These are needed because secrets can not be used in 'if' expressions
# env:
#   PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
#   TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
#   RTD_WEBHOOK_URL: ${{ secrets.RTD_WEBHOOK_URL }}
#   RTD_WEBHOOK_TOKEN: ${{ secrets.RTD_WEBHOOK_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check-out repo
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsuitesparse-dev

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Verify Environment
        run: |
          python --version
          pip --version

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==2.1.1
          poetry --version

      - name: Set project version
        run: poetry version $(git describe --tags --abbrev=0)

      - name: Install the project
        run: |
          poetry env info
          poetry install --no-interaction

      - name: Enforce linting
        run: poetry run ruff check --config ruff.toml .

      - name: Enforce formating
        run: poetry run black .

      - name: Enforce maintainance of Poetry project
        run: |
          poetry check

      # run test
      - name: Generate build
        run: poetry build

      # Run tests and generate coverage report
      - name: Code tests with Coverage
        run: |
          # Generate coverage report in XML format for the 'python' directory
          # Uses pytest-cov, requires it in dev dependencies (pyproject.toml)
          # Assumes source code is in './python' based on pyproject.toml [tool.pytest.ini_options]
          poetry run pytest -m "not gpu" --cov=python --cov-report=xml

      - name: Install MkDocs dependencies
        run: |
          poetry install --with docs

      - name: Documentation build test
        run: poetry run mkdocs build


      # Upload coverage report to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          # Ensure CODECOV_TOKEN is set as a repository secret in GitHub Settings
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          # fail_ci_if_error: true ensures the workflow fails if the upload step has an issue
          fail_ci_if_error: true
          # Optional: If coverage.xml is not in the root, specify path:
          # files: ./path/to/coverage.xml
          # Optional: Specify flags if needed
          # flags: unittests