

name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

# These are needed because secrets can not be used in 'if' expressions
# env:
#   PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
#   TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
#   RTD_WEBHOOK_URL: ${{ secrets.RTD_WEBHOOK_URL }}
#   RTD_WEBHOOK_TOKEN: ${{ secrets.RTD_WEBHOOK_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check-out repo
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsuitesparse-dev

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.11'
          channels: conda-forge
          activate-environment: argus-ci
          auto-activate-base: false

      - name: Verify Environment
        shell: bash -l {0}
        run: |
          python --version
          pip --version
          conda --version

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -n argus-ci -c conda-forge enterprise-pulsar "numpy>=2.0,<2.3" "setuptools<81" pip
          conda run -n argus-ci python -m pip install -e ".[dev,docs]" "setuptools<81"

      - name: Enforce linting
        shell: bash -l {0}
        run: conda run --no-capture-output -n argus-ci ruff check --config ruff.toml .

      - name: Enforce formatting
        shell: bash -l {0}
        run: conda run --no-capture-output -n argus-ci black --check .

      # Run tests and generate coverage report
      - name: Code tests with Coverage
        shell: bash -l {0}
        run: |
          # Generate coverage report in XML format for the 'python' directory
          # Uses pytest-cov, requires it in dev dependencies (pyproject.toml)
          # Assumes source code is in './python' based on pyproject.toml [tool.pytest.ini_options]
          conda run --no-capture-output -n argus-ci python -m pytest -m "not gpu" --cov=python --cov-report=xml

      - name: Documentation build test
        shell: bash -l {0}
        run: conda run --no-capture-output -n argus-ci mkdocs build


      # Upload coverage report to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          # Ensure CODECOV_TOKEN is set as a repository secret in GitHub Settings
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          # fail_ci_if_error: true ensures the workflow fails if the upload step has an issue
          fail_ci_if_error: true
          # Optional: If coverage.xml is not in the root, specify path:
          # files: ./path/to/coverage.xml
          # Optional: Specify flags if needed
          # flags: unittests