name: Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check-out repo
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.11'
          channels: conda-forge
          activate-environment: argus-ci
          auto-activate-base: false

      - name: Verify Environment
        shell: bash -l {0}
        run: |
          python --version
          pip --version
          conda --version

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -n argus-ci -c conda-forge "numpy>=2.0,<2.3" pip
          conda run -n argus-ci python -m pip install -e ".[dev]"

      - name: Test with pytest
        shell: bash -l {0}
        run: conda run --no-capture-output -n argus-ci python -m pytest

      # - name: Generate Coverage Report
      #   run: |
      #     conda run -n Argus coverage report -m
      #     conda run -n Argus coverage xml  # Generates coverage.xml file

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     files: coverage.xml  # Explicitly specify the coverage file
      #     fail_ci_if_error: true  # Fails the workflow if upload fails
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}