name: Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: Argus
          environment-file: env.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list

      - name: Test with pytest
        run: |
          conda run -n Argus coverage run -m pytest -v -s

      - name: Generate Coverage Report
        run: |
          conda run -n Argus coverage report -m
          conda run -n Argus coverage xml  # Generates coverage.xml file

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
           files: coverage.xml  # Explicitly specify the coverage file
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}